name: Build and release packages

on:
 push:
  tags:
    - '*'

env:
  DEBIAN_STABLE: bullseye
  PKG_NAME: scaphandre

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build packages
        run: |
          set -xe
          mkdir -p assets
          ./build.sh -i debian:${{ env.DEBIAN_STABLE }}-slim
          rename.ul .deb _${{ env.DEBIAN_STABLE }}.deb target/${{ env.PKG_NAME }}_*.deb
          mv -n target/${{ env.PKG_NAME }}_*.deb assets/

          ./build.sh -i debian:testing-slim
          rename.ul .deb _testing.deb target/${{ env.PKG_NAME }}_*.deb
          mv -n target/${{ env.PKG_NAME }}_*.deb assets/

          ./build.sh -i debian:unstable-slim
          rename.ul .deb _unstable.deb target/${{ env.PKG_NAME }}_*.deb
          mv -n target/${{ env.PKG_NAME }}_*.deb assets/

      - name: Build packages
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: assets/*.deb
